spring:
  application:
    name: sell-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LiQiongchao/config-repo.git
          username: liqiongchao
          password: Ak47;b51
          basedir: C:/Users/LIQION~1/AppData/Local/Temp/config-repo-818/
  rabbitmq:
    host: 139.224.232.41
    port: 8051


eureka:
  client:
    service-url:
      defaultZone: http://139.224.232.41:8050/eureka/

server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
#        include: "*"
        include: "bus-refresh"